"""Network observation domain model.

The network layer is 100% synthetic. ChainTrace does not have a
real-world historical source for transaction-to-IP observations.
Every network observation record carries ``is_synthetic=True``.

See CONTEXT.md §3 and DATASET.md §9–10 for generation and
provenance rules.
"""

from datetime import datetime

from pydantic import BaseModel, Field

from backend.domain.types import ScriptType


class NetworkObservation(BaseModel):
    """Synthetic network propagation observation.

    Represents a simulated observation of a Bitcoin transaction
    being propagated through the network. Generated by the
    ``generator/`` module (Phase 4).

    The ``is_synthetic`` field is hardcoded to ``True`` and cannot
    be overridden — network observations are always synthetic.
    """

    txid: int = Field(description="Elliptic++ transaction ID this observation relates to")
    src_ip: str = Field(description="Source IP address (synthetic)")
    dst_ip: str = Field(description="Destination IP address (synthetic)")
    src_port: int = Field(ge=0, le=65535)
    dst_port: int = Field(ge=0, le=65535)
    protocol: str | None = Field(default=None, description="Network protocol (e.g. TCP)")
    timestamp: datetime = Field(description="Synthetic observation timestamp")
    asn: int | None = Field(default=None, description="Autonomous System Number (local GeoIP)")
    country: str | None = Field(default=None, description="Country code (local GeoIP)")
    script_type: ScriptType | None = Field(
        default=None, description="Bitcoin script type (P2PKH, P2SH, P2WPKH, TAPROOT)"
    )

    # Provenance — always synthetic
    is_synthetic: bool = Field(
        default=True,
        description="Always True. Network layer is synthetic by design.",
    )
    generation_run_id: str | None = Field(
        default=None, description="ID of the generation run that produced this record"
    )
    scenario_id: str | None = Field(
        default=None, description="Scenario that this observation belongs to"
    )
    generator_version: str | None = Field(
        default=None, description="Version of the generator module"
    )
